openapi: 3.0.0
info:
  title: API Turnos
  description: 'Documentación para API Turnos'
  contact:
    email: gonza.fede.sanchez@gmail.com
  version: 1.0.0
servers:
- url: localhost
paths:
  /paciente:
    get:
      tags:
      - Paciente
      summary: Obtener un listado de los pacientes
      operationId: obtenerPacientes
      responses:
        200:
          description: Operación exitosa
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Paciente'
        500:
          description: Hubo un error al obtener el listado de mascotas
          content: {}
    post:
      tags:
      - Paciente
      summary: Agregar un nuevo paciente
      operationId: agregarPaciente
      requestBody:
        description: Objeto paciente a ser creado
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Paciente'
        required: true
      responses:
        201:
          description: El paciente fue creado con éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Paciente'
        400:
          description: Los datos del Paciente son incorrectos
          content: {}
        500:
          description: Ocurrió un error al crear el Paciente
          content: {}
      
  /paciente/{id}:    
    delete:
      tags: 
        - Paciente
      summary: Eliminar un paciente especifico
      operationId: eliminarPaciente
      parameters: 
        - in: path
          name: id
          required: true
          schema:
            type: string 
            example: "b11faa60-f287-11e9-8a31-dd8e324cb24b"
      responses:
        400:
          description: Operación Exitosa
          content: {}
        500:
          description: Hubo un error al eliminar el paciente
          content: {}  
    patch:
      tags:
        - Paciente
      summary: Modificar datos de un paciente por su id
      operationId: actualizarPaciente
      parameters: 
      - in: path
        name: id
        required: true
        schema:
          type: string
          example: "b11faa60-f287-11e9-8a31-dd8e324cb24b"
      responses:
        200:
          description: Operacion exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/paciente'
        500:
          description: Hubo un error al modificar el paciente
          content: {}
    option:
      tags:
        - Paciente
        summary: mostrar opciones sobre un paciente
        operationId: optionPaciente
            
  /vacunas:    
    post:
      tags:
        - Vacunas
      summary: Agregar una nueva mascota
      operationId: agregarVacuna
      requestBody:
        description: Objeto vacuna a ser creado
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Vacunas'
        required: true
      responses:
        201:
          description: La mascota fue creada con éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vacunas'
        400:
          description: Los datos de la mascota son incorrectos
          content: {}
        500:
          description: Ocurrió un error al crear la mascota
          content: {}        
components:
  schemas:
    Paciente:
      required:
      - nombre
      - apellido
      - dni
      - tel
      type: object
      properties:
        _id:
          type: string
          example: b11faa60-f287-11e9-8a31-dd8e324cb24b
        nombre:
          type: string
          example: juan
        apellido:
          type: string
          example: sanchez
        dni:
          type: int
          example: 25527987
        tel:
          type: int
          example: 4237598
        mail:
          type: string
          example: example@gmail.com
        dir:
          type: string
          example: Las Heras 243 S
        osID:
          type: string
          example: b11faa60-f287-11e9-8a31-dd8e324cb124
        f_nac:
          type: date
          example: 09/11/1990
        # vacunas:
        #   type: array
        #   items:
        #     $ref: './vacuna.yaml'
    
